// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using medibook_API.Data;

#nullable disable

namespace medibook_API.Migrations
{
    [DbContext(typeof(Medibook_Context))]
    [Migration("20251125131454_ADDSENDERRECEIVERNOTIFICATIONS")]
    partial class ADDSENDERRECEIVERNOTIFICATIONS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("medibook_API.Models.Appointments", b =>
                {
                    b.Property<int>("appointment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointment_id"));

                    b.Property<DateTime>("appointment_date")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("appointment_date");

                    b.Property<DateTime>("create_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("doctor_id")
                        .HasColumnType("INT");

                    b.Property<string>("medicine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("medicine");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<int>("nurse_id")
                        .HasColumnType("INT");

                    b.Property<int>("patient_id")
                        .HasColumnType("INT");

                    b.Property<int>("room_id")
                        .HasColumnType("INT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("appointment_id")
                        .HasName("APPOINTMENTID_PK");

                    b.HasIndex("doctor_id");

                    b.HasIndex("nurse_id");

                    b.HasIndex("patient_id");

                    b.HasIndex("room_id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("medibook_API.Models.Doctors", b =>
                {
                    b.Property<int>("doctor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doctor_id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("bio");

                    b.Property<int>("experience_years")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("specialization");

                    b.Property<int>("user_id")
                        .HasColumnType("INT");

                    b.HasKey("doctor_id")
                        .HasName("DOCTORID_PK");

                    b.HasIndex("user_id");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasCheckConstraint("CK_ExperienceYears_NonNegative", "experience_years >= 0");
                        });
                });

            modelBuilder.Entity("medibook_API.Models.FeedBacks", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feedback_id"));

                    b.Property<int>("appointment_id")
                        .HasColumnType("INT");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment");

                    b.Property<int>("doctor_id")
                        .HasColumnType("INT");

                    b.Property<string>("doctor_reply")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("doctor_reply");

                    b.Property<DateTime>("feedback_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("is_favourite")
                        .HasColumnType("bit")
                        .HasColumnName("is_favourite");

                    b.Property<int>("patient_id")
                        .HasColumnType("INT");

                    b.Property<int>("rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<DateTime>("reply_date")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("appointment_date");

                    b.HasKey("feedback_id")
                        .HasName("FEEDBACKID_PK");

                    b.HasIndex("appointment_id")
                        .IsUnique();

                    b.HasIndex("doctor_id");

                    b.HasIndex("patient_id");

                    b.ToTable("FeedBacks", t =>
                        {
                            t.HasCheckConstraint("CK_Rate_Range", "rate >= 1 AND rate <= 5");
                        });
                });

            modelBuilder.Entity("medibook_API.Models.Logs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("log_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("action_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("log_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("log_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("log_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("log_type");

                    b.Property<int>("user_id")
                        .HasColumnType("INT");

                    b.HasKey("log_id")
                        .HasName("LOGID_PK");

                    b.HasIndex("user_id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("medibook_API.Models.Notifications", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_id"));

                    b.Property<DateTime>("create_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<DateTime>("read_date")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("read_date");

                    b.Property<int>("reciever_user_id")
                        .HasColumnType("INT");

                    b.Property<int>("sender_user_id")
                        .HasColumnType("INT");

                    b.HasKey("notification_id")
                        .HasName("NOTIFICATIONID_PK");

                    b.HasIndex("reciever_user_id");

                    b.HasIndex("sender_user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("medibook_API.Models.Nurses", b =>
                {
                    b.Property<int>("nurse_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nurse_id"));

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("bio");

                    b.Property<int>("user_id")
                        .HasColumnType("INT");

                    b.HasKey("nurse_id")
                        .HasName("NURSEID_PK");

                    b.HasIndex("user_id");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("medibook_API.Models.Reports", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("report_id"));

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReportDate");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<byte[]>("report_pdf")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("report_pdf");

                    b.Property<string>("report_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("report_type");

                    b.HasKey("report_id");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("medibook_API.Models.Roles", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<DateTime>("create_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("role_id")
                        .HasName("ROLEID_PK");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("medibook_API.Models.Rooms", b =>
                {
                    b.Property<int>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("room_id"));

                    b.Property<DateTime>("create_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("room_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("room_name");

                    b.Property<string>("room_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room_type");

                    b.HasKey("room_id")
                        .HasName("ROOMID_PK");

                    b.HasIndex(new[] { "room_name" }, "ROOMNAME_UQ")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("medibook_API.Models.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("create_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email")
                        .HasAnnotation("RegularExpression", "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$");

                    b.Property<string>("email_verified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("mitrial_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mitrial_status");

                    b.Property<string>("mobile_phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("profile_image")
                        .HasMaxLength(5242880)
                        .HasColumnType("VARBINARY(MAX)")
                        .HasColumnName("profile_image");

                    b.Property<int>("role_id")
                        .HasColumnType("INT");

                    b.HasKey("user_id")
                        .HasName("USERUID_PK");

                    b.HasIndex("role_id");

                    b.HasIndex(new[] { "email" }, "USEREMAIL_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "mobile_phone" }, "USERPHONE_UQ")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Gender_Values", "gender IN ('Male', 'Female')");
                        });
                });

            modelBuilder.Entity("medibook_API.Models.Appointments", b =>
                {
                    b.HasOne("medibook_API.Models.Doctors", "Doctors")
                        .WithMany("Appointments")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Doctor_Appointment");

                    b.HasOne("medibook_API.Models.Nurses", "Nurses")
                        .WithMany("Appointments")
                        .HasForeignKey("nurse_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Nurse_Appointment");

                    b.HasOne("medibook_API.Models.Users", "Patients")
                        .WithMany("Appointments")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Patient_Appointment");

                    b.HasOne("medibook_API.Models.Rooms", "Rooms")
                        .WithMany("Appointments")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Room_Appointment");

                    b.Navigation("Doctors");

                    b.Navigation("Nurses");

                    b.Navigation("Patients");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("medibook_API.Models.Doctors", b =>
                {
                    b.HasOne("medibook_API.Models.Users", "Users")
                        .WithMany("Doctors")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_Doctor");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("medibook_API.Models.FeedBacks", b =>
                {
                    b.HasOne("medibook_API.Models.Appointments", "Appointments")
                        .WithOne("FeedBacks")
                        .HasForeignKey("medibook_API.Models.FeedBacks", "appointment_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_FeedBack");

                    b.HasOne("medibook_API.Models.Doctors", "Doctors")
                        .WithMany("FeedBacks")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Doctor_FeedBack");

                    b.HasOne("medibook_API.Models.Users", "Patients")
                        .WithMany("FeedBacks")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Patient_FeedBack");

                    b.Navigation("Appointments");

                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("medibook_API.Models.Logs", b =>
                {
                    b.HasOne("medibook_API.Models.Users", "Users")
                        .WithMany("Logs")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("medibook_API.Models.Notifications", b =>
                {
                    b.HasOne("medibook_API.Models.Users", "RecieverUsers")
                        .WithMany("RecieveNotifications")
                        .HasForeignKey("reciever_user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_RecieveNotification");

                    b.HasOne("medibook_API.Models.Users", "SendUsers")
                        .WithMany("SendNotifications")
                        .HasForeignKey("sender_user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_SenderNotification");

                    b.Navigation("RecieverUsers");

                    b.Navigation("SendUsers");
                });

            modelBuilder.Entity("medibook_API.Models.Nurses", b =>
                {
                    b.HasOne("medibook_API.Models.Users", "Users")
                        .WithMany("Nurses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_Nurse");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("medibook_API.Models.Users", b =>
                {
                    b.HasOne("medibook_API.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("medibook_API.Models.Appointments", b =>
                {
                    b.Navigation("FeedBacks")
                        .IsRequired();
                });

            modelBuilder.Entity("medibook_API.Models.Doctors", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("FeedBacks");
                });

            modelBuilder.Entity("medibook_API.Models.Nurses", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("medibook_API.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("medibook_API.Models.Rooms", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("medibook_API.Models.Users", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");

                    b.Navigation("FeedBacks");

                    b.Navigation("Logs");

                    b.Navigation("Nurses");

                    b.Navigation("RecieveNotifications");

                    b.Navigation("SendNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
